### ISSUE TITLE
QueryDeveloperDisk ImagePresent always "False"

### ISSUE THREAD

**Issue by bandy101** [exaphaser/MK.MobileDevice#1] opened 2016-01-12 01:36 UTC
as the title

**Comment by 0xFireball** [comment] 2016-04-06 20:29
I have not been seeing this issue. Could you please post your code, and if possible, more information about your usage and device? This works fine on my devices; it works by asking the image mounter service if an image is present.

**Comment by 0xFireball** [comment] 2016-05-31 04:52
I am closing this issue because it seems to be a non-issue (I have not been able to reproduce the bug). If this is actually an issue, please post a new issue and provide details as to the nature of the bug and possibly steps to duplicate it.

**Closed by 0xFireball** 2016-05-31 04:52 UTC
Labels: bug
